### ISSUE TITLE
Spring 6 compatibility - missing InstantiationAwareBeanPostProcessorAdapter class

### ISSUE THREAD

**Issue by martinsefcik** [paulcwarren/spring-content#1203]
**Describe the bug**
Spring content is not compatible with Spring 6 at least because of missing InstantiationAwareBeanPostProcessorAdapter in Spring 6.

**To Reproduce**
1. Use Spring content with Spring Boot 3 and Spring 6
2. Stores are not automatically configured because of missing InstantiationAwareBeanPostProcessorAdapter class

```
org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [internal.org.springframework.content.commons.utils.StoreInterfaceAwareBeanPostProcessor] for bean with name 'internal.org.springframework.content.commons.utils.StoreInterfaceAwareBeanPostProcessor': problem with class file or dependent class
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1508)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:684)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:652)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getType(AbstractBeanFactory.java:692)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAnnotationOnBean(DefaultListableBeanFactory.java:732)
	at org.springframework.boot.sql.init.dependency.AnnotationDependsOnDatabaseInitializationDetector.detect(AnnotationDependsOnDatabaseInitializationDetector.java:36)
	at org.springframework.boot.sql.init.dependency.DatabaseInitializationDependencyConfigurer$DependsOnDatabaseInitializationPostProcessor.detectDependsOnInitializationBeanNames(DatabaseInitializationDependencyConfigurer.java:148)
	at org.springframework.boot.sql.init.dependency.DatabaseInitializationDependencyConfigurer$DependsOnDatabaseInitializationPostProcessor.postProcessBeanFactory(DatabaseInitializationDependencyConfigurer.java:111)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:358)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:194)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:745)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:565)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291)
	at sk.letanovce.api.LetanovceApiApplication.main(LetanovceApiApplication.java:22)
Caused by: java.lang.NoClassDefFoundError: org/springframework/beans/factory/config/InstantiationAwareBeanPostProcessorAdapter
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1013)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:495)
	at java.base/java.lang.Class.forName(Class.java:474)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:283)
	at org.springframework.beans.factory.support.AbstractBeanDefinition.resolveBeanClass(AbstractBeanDefinition.java:461)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doResolveBeanClass(AbstractBeanFactory.java:1569)
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1502)
	... 18 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.beans.factory.config.InstantiationAwareBeanPostProcessorAdapter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 34 common frames omitted
```

**Expected behavior**
Stores should be correctly initialized by auto-configurations

**Comment by paulcwarren** [comment]
Hi @martinsefcik , thanks for the rep. rt. You are right.  SC does not yet support Spring 6.  Its on my radar for early next year.

**Comment by martinsefcik** [comment]
@paulcwarren  by "next year" you mean 2023 or 2024 ? :)

**Comment by paulcwarren** [comment]
Yeah, I meant 2023.   

I wonder how many Spring Content users are already moving to SB 3/SF 6?

**Comment by dhirajbadu** [comment]
I am also facing the same issue. Is there any updates?

<img width="796" alt="Screenshot 2023-03-20 at 8 56 21 PM" src="https://user-images.githubusercontent.com/46293891/226383968-f659ef20-b852-4d82-ab8c-e484da77988d.png">

**Comment by dhirajbadu** [comment]
Could you please look into the https://github.com/paulcwarren/spring-content/pull/1312/ pr?

**Comment by paulcwarren** [comment]
Many thanks for the PR @dhirajbadu.  That issue is already fixed in my [SB3 migration PR](https://github.com/paulcwarren/spring-content/pull/1288).  That I will be finishing up this week.

**Comment by dhirajbadu** [comment]
Great news @paulcwarren thank you

**Comment by paulcwarren** [comment]
The 3.x release line of Spring Content is implemented against Spring Boot 3/Spring Framework 6.
