### ISSUE TITLE
ClientAbortException on browser

### ISSUE THREAD

**Issue by hnpanther** [paulcwarren/spring-content#349]
i am facing this problem when pause or forward video in browser
`org.apache.catalina.connector.ClientAbortException: java.io.IOException: An established connection was aborted by the software in your host machine
at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:351) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
at org.apache.catalina.connector.OutputBuffer.flushByteBuffer(OutputBuffer.java:776) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
at org.apache.catalina.connector.OutputBuffer.append(OutputBuffer.java:681) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
at org.apache.catalina.connector.OutputBuffer.writeBytes(OutputBuffer.java:386) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
at org.apache.catalina.connector.OutputBuffer.write(OutputBuffer.java:364) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
at org.apache.catalina.connector.CoyoteOutputStream.write(CoyoteOutputStream.java:96) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
at org.springframework.util.StreamUtils.copyRange(StreamUtils.java:203) ~[spring-core-5.2.8.RELEASE.jar:5.2.8.RELEASE]
at org.springframework.http.converter.ResourceRegionHttpMessageConverter.writeResourceRegion(ResourceRegionHttpMessageConverter.java:159) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
at org.springframework.http.converter.ResourceRegionHttpMessageConverter.writeInternal(ResourceRegionHttpMessageConverter.java:136) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
...`
my code and config for spring-content:
https://github.com/hnpanther/spring-boot-video-streaming/tree/master/src/main/java/ir/hadi/springbootvideostreaming/config

**Comment by paulcwarren** [comment]
This usually indicates that the client has chosen to close the connection.  I assume the client in this case is a browser?  What are you using?  Chrome?

**Comment by hnpanther** [comment]
> This usually indicates that the client has chosen to close the connection. I assume the client in this case is a browser? What are you using? Chrome?

yes client is a browser. i'm testing with Chrome and Firefox also test with a download manager for devide download to multipart.
im getting same exception:
`ERROR 10480 --- [nio-8080-exec-7] i.o.s.c.r.c.StoreRestController          : Unable to handle request

org.apache.catalina.connector.ClientAbortException: java.io.IOException: An existing connection was forcibly closed by the remote host
	at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:351) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.connector.OutputBuffer.flushByteBuffer(OutputBuffer.java:776) ~[tomcat-embed-core-9.0.37.jar:9.0.37]`

**Comment by hnpanther** [comment]
when I get the rest endpoints and video streaming support for free and skip forward video in browser or download video with download manager,this exception occurs:
`org.apache.catalina.connector.ClientAbortException: java.io.IOException: An established connection was aborted by the software in your host machine at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:351) ~[tomcat-embed-core-9.0.37.jar:9.0.37] at org.apache.catalina.connector.OutputBuffer.flushByteBuffer(OutputBuffer.java:776) ~[tomcat-embed-core-9.0.37.jar:9.0.37] at org.apache.catalina.connector.OutputBuffer.append(OutputBuffer.java:681) ~[tomcat-embed-core-9.0.37.jar:9.0.37] at org.apache.catalina.connector.OutputBuffer.writeBytes(OutputBuffer.java:386) ~[tomcat-embed-core-9.0.37.jar:9.0.37] at org.apache.catalina.connector.OutputBuffer.write(OutputBuffer.java:364) ~[tomcat-embed-core-9.0.37.jar:9.0.37] at org.apache.catalina.connector.CoyoteOutputStream.write(CoyoteOutputStream.java:96) ~[tomcat-embed-core-9.0.37.jar:9.0.37] at org.springframework.util.StreamUtils.copyRange(StreamUtils.java:203) ~[spring-core-5.2.8.RELEASE.jar:5.2.8.RELEASE] at org.springframework.http.converter.ResourceRegionHttpMessageConverter.writeResourceRegion(ResourceRegionHttpMessageConverter.java:159) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE] at org.springframework.http.converter.ResourceRegionHttpMessageConverter.writeInternal(ResourceRegionHttpMessageConverter.java:136) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE] ...
`
my code:
```
@Configuration
@EnableFilesystemStores
public class StoreConfig {

    public File fileSystemRoot() throws IOException {
        return new File("local_storage/video");
    }

    @Bean
    public FileSystemResourceLoader fsResourceLoader() throws Exception
    {
        return new FileSystemResourceLoader(fileSystemRoot().getAbsolutePath());
    }

}
@StoreRestResource(path = "videosrc")
public interface VideoContentStore extends ContentStore<VideoFile, String> {
}

@RepositoryRestResource
public interface VideoFileRepository extends JpaRepository<VideoFile, Long> {


}
```

**Comment by paulcwarren** [comment]
Thanks.  Will investigate.

**Comment by paulcwarren** [comment]
Looks like when the client is aborts a connection - which it is quite at liberty to do at any time - the StoreRestController is treating that as a genuine error condition when it shouldn't be.
