### ISSUE TITLE
IllegalStateException when following link-rel 'content' with fullyQualifiedLinks=true

### ISSUE THREAD

**Issue by tgeens** [paulcwarren/spring-content#387]
Using `spring-content-rest-boot-starter` version `1.1.0.M4`, I enabled `spring.content.rest.fullyQualifiedLinks=true` to get fully qualified links.

That leads to the following set of hypermedia links:

```
"_links": {
    "self": {
        "href": "http://localhost:44437/files/1"
    },
    "file": {
        "href": "http://localhost:44437/files/1"
    },
    "content": {
        "href": "http://localhost:44437/files/1/content"
    }
}
```

I should be able to follow the `content` link for the endpoint to multipart PUT a file ?

This leads to the following stacktrace:
```
java.lang.IllegalStateException: Store for property contentId not found
	at internal.org.springframework.content.rest.controllers.StoreHandlerMethodArgumentResolver.resolveProperty(StoreHandlerMethodArgumentResolver.java:244) ~[spring-content-rest-1.1.0.M4.jar:na]
	at internal.org.springframework.content.rest.controllers.ResourceHandlerMethodArgumentResolver.resolveArgument(ResourceHandlerMethodArgumentResolver.java:76) ~[spring-content-rest-1.1.0.M4.jar:na]
	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:121) ~[spring-web-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:167) ~[spring-web-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134) ~[spring-web-5.2.9.RELEASE.jar:5.2.9.RELEASE]
```

I have this reproduced in a unit tests in a fork of the 'getting-started' project here: https://github.com/tgeens/spring-content-gettingstarted/commit/d0ecf9b1cede3ee378bcf42aae2fb289619058ff

**Comment by paulcwarren** [comment]
I made a PR back to your fork so you can see the changes that verify the fix.
