### ISSUE TITLE
Support for spring-cloud-aws 2

### ISSUE THREAD

**Issue by pulse00** [paulcwarren/spring-content#46]
We're upgrading our applications to spring boot 2 and spring 5 which causes our apps containing spring-content to fail with `java.lang.ClassNotFoundException: org.springframework.cloud.aws.core.io.s3.SimpleStorageResourceLoader` 

I've created a sample project demonstrating the issue: https://github.com/pulse00/spring-content-boot-2.

I've seen a spring-boot-2 branch (https://github.com/paulcwarren/spring-content/tree/wip/springboot2), which has no recent activity.

Are we missing something? If not, can we help migrating to spring boot 2 / spring-cloud 2?

**Comment by paulcwarren** [comment]
Hi @pulse00.  I pushed a fix to 0.3.0-SNAPSHOT and tested this against your `spring-boot-2` sample which seemed to work.  If you want to try it on a real project and let me know if it fixes it there then I can cut a release with the fix for you.  ltk

**Comment by pulse00** [comment]
HI @paulcwarren - thanks for the fix! I've updated our spring-content version to 0.3.0-SNAPSHOT, but now i'm seeing this exception:

```
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'transactionManager' available: No matching PlatformTransactionManager bean found for qualifier 'transactionManager' - neither qualifier match nor bean name match!
	at org.springframework.beans.factory.annotation.BeanFactoryAnnotationUtils.qualifiedBeanOfType(BeanFactoryAnnotationUtils.java:109)
	at org.springframework.beans.factory.annotation.BeanFactoryAnnotationUtils.qualifiedBeanOfType(BeanFactoryAnnotationUtils.java:68)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.determineQualifiedTransactionManager(TransactionAspectSupport.java:406)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.determineTransactionManager(TransactionAspectSupport.java:387)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:284)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy204.setContent(Unknown Source)
	at at.erpel.webedi.test.routeBeans.ContentExtractorTest.testContentExtractionWithUnknownDocType(ContentExtractorTest.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:73)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:83)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	... 29 more```

This looks like it comes from the JPAStore, but we haven't configured. Does this need to be excluded now?

**Comment by paulcwarren** [comment]
Whoops.  It looks like a commit from an issue branch somehow made it onto master.  I can revert that commit.  But just so I can test it can you explain your setup a little bit.  This got through our tests so we must not have a test that mirrors your setup.  

From the stack trace it looks like your test is calling `ContentStore.setContent` meaning you have an associative store and associating content with entities which implies a database.  Are you something other than a JPA database or in your configuration is the transaction manager bean called something other than `transactionManager`?

**Comment by pulse00** [comment]
@paulcwarren i'll update the testcase project and get back to you.

**Comment by paulcwarren** [comment]
Thanks for the info.  Although I think it is highly likely it's now working because of the reverted code.  All of our integration tests (other than spring content mongodb/gridfs) use a JPA db so I think we'll switch that up and use mongodb for the sc s3 test. 

Let me know either way and we'll either investigate further, or close out this issue.

**Comment by paulcwarren** [comment]
OK.  We pushed 0.3.0 yesterday.  Should be available in maven central.
