### ISSUE TITLE
FileNotFoundException: S3StoreConfiguration.class

### ISSUE THREAD

**Issue by acanogal** [paulcwarren/spring-content#558]
In my pom.xml I have included the dependency:
		<dependency>
			<groupId>com.github.paulcwarren</groupId>
			<artifactId>spring-content-fs-boot-starter</artifactId>
			<version>1.2.4</version>
		</dependency>

I just want to use Spring Content Filesystem, for now. In my project I use SNS from Amazon and have a lot of AWS dependencies included, but not for use with Spring Content.

Why do I get an error when starting my project looking for the S3 configuration?

In my resource file I have the variable defined:
spring.content.fs.filesystemRoot=upload-dir/user-files

Caused by: java.io.FileNotFoundException: class path resource [internal/org/springframework/content/s3/config/S3StoreConfiguration.class] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:180) ~[spring-core-5.3.3.jar:5.3.3]
	at org.springframework.core.type.classreading.SimpleMetadataReader.getClassReader(SimpleMetadataReader.java:55) ~[spring-core-5.3.3.jar:5.3.3]
	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:49) ~[spring-core-5.3.3.jar:5.3.3]
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:103) ~[spring-core-5.3.3.jar:5.3.3]

**Comment by paulcwarren** [comment]
Hi @cangol,

I'm guessing that you have `com.amazonaws.services.s3.AmazonS3Client` on your classpath?  

And that is triggering Spring Content S3 auto configuration to trigger.

You can try excluding S3ContentAutoConfiguration in your `SpringBootApplication`:

```
@SpringBootApplication(exclude = {
        S3ContentAutoConfiguration.class})
public class Application {
```

**Comment by acanogal** [comment]
Hi Paul!

Thank you very much for your help. I have done what you have commented and it already works. I am going to continue exploring the great project you have developed.

By the way, my nick is acanogal! ;-))

**Comment by paulcwarren** [comment]
No problem @acanogal.  Glad we were able to find a workaround.  Sorry for the typo.
