### ISSUE TITLE
'No converter found' for ID in REST endpoint

### ISSUE THREAD

**Issue by stefan-ka** [paulcwarren/spring-content#638]
Hi @paulcwarren 

I have a question regarding spring-content-rest...

I'm using spring-content to store media files, for example MP4 files, on a file system. That works perfectly and was really simple to set up!

Now I  need an endpoint to stream my MP4 videos in the browser. As I have read that this is already supported by spring-content-rest, I want to use it... I'm however struggling with setting it up; maybe you can help?

The definition of my media store is simple:

```java
@StoreRestResource(path = "media-file-contents")
@RestResource(exported = false)
public interface SpringContentMediumFileStore extends ContentStore<MediumFileContentJpaEntity, MediumFileContentJpaId> {
}
```
The JPA entity as well:

```java
@InfrastructureRing
@Entity
@Table(name = "MEDIUMFILECONTENTS")
public class MediumFileContentJpaEntity implements MediumFileContent {

    @EmbeddedId
    private MediumFileContentJpaId id;

    @ContentId
    @Column(name = "content_id")
    private String contentId;

    @ContentLength
    @Column(name = "content_length")
    private long contentLength;

    @MimeType
    @Column(name = "mime_type")
    private String mimeType = "video/mp4";
}
```

Writing to the file store and reading from it works perfectly fine...
The point where I am struggling with my endpoint setup is my ID, which basically consists of two other IDs:

```java
@Embeddable
public class MediumFileContentJpaId implements MediumFileContentId, Serializable {

    @AttributeOverride(name = "value", column = @Column(name = "supporting_medium_id"))
    private SupportingMediumId mediumId;

    @AttributeOverride(name = "value", column = @Column(name = "medium_file_id"))
    private MediumFileId fileId;
}
```

`SupportingMediumId` and `MediumFileId` are just value objects that wrap UUID strings.

Via the `ContentRestConfigurer` I set the base URI for the endpoint to `/contentApi`:

```java
    @Bean
    public ContentRestConfigurer contentRestConfigurer() {
        return new ContentRestConfigurer() {
            @Override
            public void configure(RestConfiguration config) {
                config.setBaseUri(URI.create("/contentApi"));
            }
        };
    }
```

Here comes my problem... When I call the endpoint with my two IDs, like `localhost:8080/content/Api/media-file-contents/{supportingMediumId}/{mediumFileId}`, or just with any string `localhost:8080/content/Api/media-file-contents/{just-any-string}`, I get the following exception:

```
org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [ch.my_customer.infrastructure.media.content.MediumFileContentJpaId]
	at org.springframework.core.convert.support.GenericConversionService.handleConverterNotFound(GenericConversionService.java:322) ~[spring-core-5.3.2.jar:5.3.2]
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:195) ~[spring-core-5.3.2.jar:5.3.2]
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:175) ~[spring-core-5.3.2.jar:5.3.2]
	at internal.org.springframework.content.rest.controllers.resolvers.EntityResolver.findOne(EntityResolver.java:140) ~[spring-content-rest-1.2.5.jar:na]
	at internal.org.springframework.content.rest.controllers.resolvers.EntityResolver.resolve(EntityResolver.java:82) ~[spring-content-rest-1.2.5.jar:na]
	at internal.org.springframework.content.rest.controllers.StoreHandlerMethodArgumentResolver.resolveArgument(StoreHandlerMethodArgumentResolver.java:99) ~[spring-content-rest-1.2.5.jar:na]
	at internal.org.springframework.content.rest.controllers.ResourceHandlerMethodArgumentResolver.resolveArgument(ResourceHandlerMethodArgumentResolver.java:38) ~[spring-content-rest-1.2.5.jar:na]
```

I already tried to tackle this in two ways...

1) I created a `org.springframework.core.convert.converter.Converter`: 

```java
@Component
public class StringToMediumFileContentJpaIdConverter implements Converter<String, MediumFileContentJpaId> {
    @Override
    public MediumFileContentJpaId convert(String input) {
        // impl. that returns a MediumFileContentJpaId
    }
}
```

2. I registered a converter in the `FilesystemStoreConfigurer`:

```java
    @Bean
    public FilesystemStoreConfigurer configurer() {
        return new FilesystemStoreConfigurer() {
            @Override
            public void configureFilesystemStoreConverters(ConverterRegistry registry) {
                registry.addConverter(new Converter<String, MediumFileContentJpaId>() {
                    @Override
                    public MediumFileContentJpaId convert(String s) {
                        // impl. that returns a MediumFileContentJpaId
                    }
                });
            }
        };
    }
```

Nothing helped so far... Can you help me out here? How do I have to configure spring-content-rest so that I can stream my MP4s under an endoint that takes my two nested IDs as parameters (`localhost:8080/content/Api/media-file-contents/{supportingMediumId}/{mediumFileId}`)? 
Alternatively I would also be happy if I could call the endpoint with the `contentId`, but that doesn't seem to work as well (because it looks like the framework is always expecting a `MediumFileContentJpaId` based on my interface).

Thanks in advance!
Stefan

**Comment by stefan-ka** [comment]
@paulcwarren 

I'm not sure, but I think there is a problem here:

https://github.com/paulcwarren/spring-content/blob/03bb45526f5c1aea3d12b4677f359573d64fb230/spring-content-rest/src/main/java/internal/org/springframework/content/rest/controllers/resolvers/EntityResolver.java#L140

You create a new `DefaultConversionService` instead of using the corresponding spring beans?

At least I assume that this is the reason why my converter for the Id is not found...

Best regards,
Stefan

**Comment by paulcwarren** [comment]
Thanks for researching.  I will take a look at this soonest.  The only comment/question I have about the initial report is that the format of the URI.  Splitting the ID over two segments of the URI looks problematic.  I would image you would have to do something like:

`localhost:8080/content/Api/media-file-contents/{supportingMediumId}-{mediumFileId}`

Otherwise, I am not sure how we would ever "know" the ID was the last two segments of the URI.  Question, is that something that Spring Data REST does support?

**Comment by stefan-ka** [comment]
I don't know whether this is supported by Spring Data REST... Maybe it would be possible if you provide an approach how one can easily define the desired controllers/endpoints and the mapping to the content store manually (at the moment I am also missing the possibility to only activate some specific endpoints and HTTP verbs; for example if I just want to activate a GET endpoint for streaming, but PUT, POST, etc. should not be allowed).

However, if I could do it with `{supportingMediumId}-{mediumFileId}` as suggested, that would be absolutely fine for me. The possibility to use a custom converter to convert the Id-segment (one string) into my ID value object would already help a lot.

**Comment by paulcwarren** [comment]
Ok.   So, for ContentStore's, Spring Content REST leans pretty heavily on Spring Data so I'd first like to figure out if/how Spring Data/REST supports this use case and then figure out if/how Spring Content/REST might support it.  Once I get a better understanding we might be able to tease the two apart so that you don't have to use Spring Data REST yourself.

To that end I put together this [sample  project](https://github.com/paulcwarren/issue-638) to check that I understand your data model.  This uses the second approach above.  You should be able to run this and 

` curl -X POST -H 'Content-Type:application/hal+json' -d '{}' http://localhost:8080/media-files/` 

to create a new entity.  

Haven't done anything with content yet.  Let me know if this is representative, or not.

**Comment by stefan-ka** [comment]
Yes, that's representative.

(Basically, I just want to be able to use a custom Java object for the entity ID. Currently, this is not possible with Spring Content; as it has to be a String, UUID, or anything else that can be converted with the default converters provided by Spring.)
