### ISSUE TITLE
Error creating bean with name 'amazonS3'

### ISSUE THREAD

**Issue by thijslemmens** [paulcwarren/spring-content#667]
**Describe the bug**
Spring Content application is failing to start without valid S3 configuration, even though I don't want to use S3 for local development.

**To Reproduce**
1. Update to spring content 1.2.6
2. Add the starter "com.github.paulcwarren:spring-content-s3-boot-starter"
3. Do not provide valid configuration
4. Start the application

Exception: 
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[ERROR] 2021-11-10 10:39:27.267 [restartedMain]  o.s.b.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'amazonS3' defined in class path resource [internal/org/springframework/content/s3/boot/autoconfigure/S3ContentAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.amazonaws.services.s3.AmazonS3]: Factory method 'amazonS3' threw exception; nested exception is com.amazonaws.SdkClientException: Unable to find a region via the region provider chain. Must provide an explicit region in the builder or setup environment to supply a region.
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332)
	at eu.xenit.neutra.neutraarchive.NeutraArchiveApplication.main(NeutraArchiveApplication.java:30)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.amazonaws.services.s3.AmazonS3]: Factory method 'amazonS3' threw exception; nested exception is com.amazonaws.SdkClientException: Unable to find a region via the region provider chain. Must provide an explicit region in the builder or setup environment to supply a region.
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 24 common frames omitted
Caused by: com.amazonaws.SdkClientException: Unable to find a region via the region provider chain. Must provide an explicit region in the builder or setup environment to supply a region.
	at com.amazonaws.client.builder.AwsClientBuilder.setRegion(AwsClientBuilder.java:462)
	at com.amazonaws.client.builder.AwsClientBuilder.configureMutableProperties(AwsClientBuilder.java:424)
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
	at internal.org.springframework.content.s3.boot.autoconfigure.S3ContentAutoConfiguration.amazonS3(S3ContentAutoConfiguration.java:54)
	at internal.org.springframework.content.s3.boot.autoconfigure.S3ContentAutoConfiguration$$EnhancerBySpringCGLIB$$83ad0c1.CGLIB$amazonS3$0(<generated>)
	at internal.org.springframework.content.s3.boot.autoconfigure.S3ContentAutoConfiguration$$EnhancerBySpringCGLIB$$83ad0c1$$FastClassBySpringCGLIB$$2cc5f9a7.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at internal.org.springframework.content.s3.boot.autoconfigure.S3ContentAutoConfiguration$$EnhancerBySpringCGLIB$$83ad0c1.amazonS3(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 25 common frames omitted

**Expected behavior**
Application starting correctly as the AmazonS3 bean is not used.

**Additional context**
On 1.2.5, the same application was working.

**Comment by thijslemmens** [comment]
Works again if I create my own dummy AmazonS3 bean. Is there a way to turn of the automatic bean creation?

**Comment by paulcwarren** [comment]
Hey @thijslemmens, 

I think this was the conversation I was trying to have [here](https://github.com/paulcwarren/spring-content/issues/645#issuecomment-948249020).  

I based [my properties implementation](https://github.com/paulcwarren/spring-content/blob/66f6fd24e0c5eb46ae9d62c510087540cebbec50/spring-content-autoconfigure/src/main/java/internal/org/springframework/content/s3/boot/autoconfigure/S3ContentAutoConfiguration.java#L37) on [your suggested code](https://github.com/paulcwarren/spring-content/issues/645#issuecomment-948329693) and I understood your comment to mean that your code didn't need to set a REGION environment variable.  I didn't quite understand why that was because I have to [set it](https://github.com/paulcwarren/spring-content/blob/66f6fd24e0c5eb46ae9d62c510087540cebbec50/spring-content-autoconfigure/src/test/java/org/springframework/content/s3/boot/ContentS3AutoConfigurationTest.java#L52) in my tests.

So, how does your original code get away with not setting a REGION env var then?  Any ideas?   Were you perhaps using an older version of the amazon s3 sdk?  Or something like that?

**Comment by thijslemmens** [comment]
Hello @paulcwarren 

The amazon S3 sdk version is coming from `spring-content-s3-boot-starter`.
My suggested code is only executed when `spring.content.storage.type=s3`. Now, I'm in the local test case where I use `filesystem`. So this is a case where I don't actually try to configure a working S3 setup.

kind regards

Thijs

**Comment by paulcwarren** [comment]
Yeah, but your original code where you didnt need to set the REGION env var.  What version of s3 libraries was that using?

**Comment by thijslemmens** [comment]
Both the previous and the current version of the `spring-content-s3-boot-starter` use `com.amazonaws:aws-java-sdk-s3:1.11.792`.  I didn't change anything else, and I did not specify the dependency explicitly so I use that version.

**Comment by paulcwarren** [comment]
> I can confirm that setting the AWS_REGION env variable works. I use that as a workaround for now.
Which is dumb because presumably region is a meaningless construct in your topology?

> Both the previous and the current version of the spring-content-s3-boot-starter use com.amazonaws:aws-java-sdk-s3:1.11.792. I didn't change anything else, and I did not specify the dependency explicitly so I use that version.
Interesting.  Thanks for the update.  I am not sure what else to check then.  But it seems we may just have to deal with region.  If I cant find a way to side step it then perhaps we can add it to the set of properties?

**Comment by paulcwarren** [comment]
I cant see any way around this. 

From the docs it seems you have to specify a region.  S3 obviously favors S3.  S3 is global, obviously, but buckets are regional and it is therefore more efficient if you talk to the relevant "regional" endpoint where you bucket(s) lives.  Setting region is a shorthand way of telling S3 which endpoint to talk to so they dont have to worry about long URIs.

When creating a client using their builder api (everything other way of creating an AmazonS3Client is deprecated AFAICT) one would specify the region with `withRegion`.  But (a) that makes less/no sense with non s3 platforms and (b) if you are also specifying a `withEndpointConfiguration` - which we have to here as we are using a non s3 platform - then you can't also call `withRegion`.  If we do we get a "cant call both" exception.

So, what we are doing is right I think.   And the new builder api, when compared to the older constructor approach of creating AmazonS3 objects, just works different.  The first link below basically concludes the same thing.

Actually, now I understand things a little better I would argue that I like what we are doing here a lot less as it strongly favors non s3 platforms which probably isn't the general use case.  We probably should also offer a region property and the code should use that OR the endpoint.  But, when using the endpoint you also need that AWS_REGION env var set.  Or specified in one of the aws config files in the machine's home directory (if you prefer).

Here are some of the resources I happened across whilst investigating in case useful.  

- https://stackoverflow.com/questions/46697047/amazons3clientbuilder-defaultclient-fails-to-account-for-region
- https://github.com/aws/aws-sdk-java/issues/1284
- https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-region-selection.html  

And maybe you can spot something that I didnt.
