### ISSUE TITLE
Add support for Spring Boot 2.2.0

### ISSUE THREAD

**Issue by paulcwarren** [paulcwarren/spring-content#71]
@Arya raised [this issue](https://github.com/paulcwarren/spring-content-examples/issues/3) against spring-content-examples.  

We should prep for and add support Spring Boot 2.2.0.   However, 2.2.0 depends on Spring Moore which depends on `spring-hateoas` 1.0.0 with significantly updated its API with backward incompatible changes.

**Comment by paulcwarren** [comment]
I decided that I am going to release this as a `1.0.0.M1` when ready.  A `1.0` is probably overdue, at least from a functionality perspective.  I did want to clean up the REST module amongst other things but if we are to support SB 2.2.0 which pulls in spring-hateoas and its breaking changes I need to get onto a versioning strategy where we can mirror real the spring projects.

**Comment by paulcwarren** [comment]
Currently blocked on [DATAREST-1397](https://jira.spring.io/browse/DATAREST-1397).

**Comment by davidm76** [comment]
Hi @paulcwarren ,
I've just recently integrated spring-content into my current project.  It's amazing, and saved me a ton of work!  Thanks for your efforts.

However, to get round an issue in spring-data-rest, I'm looking to upgrade to Spring Boot 2.2 M1.  Do you have an idea of when support might be added?

Thanks.

David.

**Comment by paulcwarren** [comment]
Hi @davidm76,

Firstly, thanks for using Spring Content. 

Unfortunately, Spring Boot 2.2.M1 has the aforementioned but above (DATAREST-1397).   

That said, 2.2 M5 depends on Spring Data Moore RC2 that, I believe, will have the bug fix for DATAREST-1397.

So, I think we would be in a position to release our 1.0.0.M1 based on 2.2M5 and Moore RC2.  This will presumably have the bug fix you need to.  Is there a reason you wanted to pin to 2.2.M1?  Or is 2.2.M5 fine too?

**Comment by davidm76** [comment]
Thanks for getting back to me @paulcwarren .  Yes, 2.2.M5 would work.  M1 was I typo!
Cheers.
David.

**Comment by paulcwarren** [comment]
OK.  Sounds good.  So, I've got an upcoming 0.10.0 release.  Then I'll merge the 0.10.0 changes across and do a 1.1.0.M1 release for you.  Give me a couple of weeks to tidy some things up.

**Comment by davidm76** [comment]
Thanks @paulcwarren , it's very much appreciated.

**Comment by davidm76** [comment]
Thanks @paulcwarren 
I'll give it a try.

**Comment by davidm76** [comment]
Hi @paulcwarren ,

I've upgraded my POM as follows:

```xml
   <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.2.0.M5</version>
    </parent>
```

```xml
     <dependency>
            <groupId>com.github.paulcwarren</groupId>
            <artifactId>spring-content-fs-boot-starter</artifactId>
            <version>1.0.0.M1</version>
        </dependency>
        <dependency>
            <groupId>com.github.paulcwarren</groupId>
            <artifactId>spring-content-rest-boot-starter</artifactId>
            <version>1.0.0.M1</version>
        </dependency>
        <dependency>
            <groupId>com.github.paulcwarren</groupId>
            <artifactId>spring-content-jpa</artifactId>
            <version>1.0.0.M1</version>
        </dependency>
```

I no longer get the ClassNotFoundException, which is great, however, my ContentStore bean does not seems to have been created.

I have the following ContentStore:

```java
@StoreRestResource
public interface ScaleableVectorContentStore extends ContentStore<SymbolVector, String> {
}
```

However, the allocation fails to start:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 6 of constructor in com.yambay.vizserver.services.SymbolService required a bean of type 'com.yambay.vizserver.domain.repositories.ScaleableVectorContentStore' that could not be found.


Action:

Consider defining a bean of type 'com.yambay.vizserver.domain.repositories.ScaleableVectorContentStore' in your configuration.


Process finished with exit code 1
```

It looks like the interface hasn't been inflated.

Any ideas?

Thanks.

David.

**Comment by davidm76** [comment]
Hi @paulcwarren 

I tried removing spring-content-fs-boot-starter.

If I do that the application fails to start with the following exception:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'halLinkDisocoverer' defined in class path resource [org/springframework/hateoas/mediatype/hal/HalMediaTypeConfiguration.class]: Post-processing of merged bean definition failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [org.springframework.hateoas.client.JsonPathLinkDiscoverer] from ClassLoader [sun.misc.Launcher$AppClassLoader@18b4aac2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:572) ~[spring-beans-5.2.0.RC1.jar:5.2.0.RC1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.0.RC1.jar:5.2.0.RC1]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.0.RC1.jar:5.2.0.RC1]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.0.RC1.jar:5.2.0.RC1]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.0.RC1.jar:5.2.0.RC1]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.0.RC1.jar:5.2.0.RC1]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:877) ~[spring-beans-5.2.0.RC1.jar:5.2.0.RC1]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877) ~[spring-context-5.2.0.RC1.jar:5.2.0.RC1]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.2.0.RC1.jar:5.2.0.RC1]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.0.M5.jar:2.2.0.M5]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:746) [spring-boot-2.2.0.M5.jar:2.2.0.M5]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:396) [spring-boot-2.2.0.M5.jar:2.2.0.M5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.2.0.M5.jar:2.2.0.M5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1225) [spring-boot-2.2.0.M5.jar:2.2.0.M5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1214) [spring-boot-2.2.0.M5.jar:2.2.0.M5]
	at com.yambay.vizserver.VizServerApplication.main(VizServerApplication.java:43) [classes/:na]
Caused by: java.lang.IllegalStateException: Failed to introspect Class [org.springframework.hateoas.client.JsonPathLinkDiscoverer] from ClassLoader [sun.misc.Launcher$AppClassLoader@18b4aac2]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:476) ~[spring-core-5.2.0.RC1.jar:5.2.0.RC1]
	at org.springframework.util.ReflectionUtils.doWithLocalMethods(ReflectionUtils.java:317) ~[spring-core-5.2.0.RC1.jar:5.2.0.RC1]
	at org.springframework.orm.jpa.support.PersistenceAnnotationBeanPostProcessor.buildPersistenceMetadata(PersistenceAnnotationBeanPostProcessor.java:437) ~[spring-orm-5.2.0.RC1.jar:5.2.0.RC1]
	at org.springframework.orm.jpa.support.PersistenceAnnotationBeanPostProcessor.findPersistenceMetadata(PersistenceAnnotationBeanPostProcessor.java:408) ~[spring-orm-5.2.0.RC1.jar:5.2.0.RC1]
	at org.springframework.orm.jpa.support.PersistenceAnnotationBeanPostProcessor.postProcessMergedBeanDefinition(PersistenceAnnotationBeanPostProcessor.java:335) ~[spring-orm-5.2.0.RC1.jar:5.2.0.RC1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyMergedBeanDefinitionPostProcessors(AbstractAutowireCapableBeanFactory.java:1095) ~[spring-beans-5.2.0.RC1.jar:5.2.0.RC1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:569) ~[spring-beans-5.2.0.RC1.jar:5.2.0.RC1]
	... 15 common frames omitted
Caused by: java.lang.NoClassDefFoundError: com/jayway/jsonpath/JsonPath
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[na:1.8.0_212]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2729) ~[na:1.8.0_212]
	at java.lang.Class.getDeclaredMethods(Class.java:2003) ~[na:1.8.0_212]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:458) ~[spring-core-5.2.0.RC1.jar:5.2.0.RC1]
	... 21 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.jayway.jsonpath.JsonPath
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_212]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[na:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_212]
	... 25 common frames omitted
```

The strange thing is, when I look at the dependencies of spring-content-fs-boot-starter, |I can't see  JsonPath  included.

If I add JsonPath into my POM, I still get the same issue.

Not sure what's going on.

Thanks.

David.

**Comment by paulcwarren** [comment]
Hi David,

I wonder if your jsonpath jar library got corrupted during download?  From a dependency perspective it looks like it is there but when the classloader actually tries to load classes from it, it can't?  I have seen this plenty over the years.

As for `spring-content-fs-boot-starter` "fixing" it.  Not sure either.  If it is corrupted then maybe adding it is changing the classpath just enough to drag in a different version of jsonpath (an uncorrupted version) or something like that?  

If that isnt it then can you run `mvn dependency:tree` and post the output?  Maybe I can spot something in that.

**Comment by davidm76** [comment]
Hi @paulcwarren ,
I got it sorted.  I was using `json-path` already in my integration tests, so it has a scope of `test`, effectively meaning it was removed from the class path at runtime.  It's all working.

Thanks so much for you're help.

David.

**Comment by modikanisha** [comment]
Hello @paulcwarren ,
Sir I need your help. I am upgrading the springboot version to 2.2.2. Currently I am facing issue which described in this link [issue](https://github.com/spring-cloud/spring-cloud-netflix/issues/3732).

Please help me.It would be a grateful.TIA.

**Comment by silentsnooc** [comment]
@modikanisha I think what he did was changing 

```xml
<dependency>
    <groupId>com.jayway.jsonpath</groupId>
    <artifactId>json-path</artifactId>
    <scope>test</scope>
</dependency>
``` 

to 

```
<dependency>
    <groupId>com.jayway.jsonpath</groupId>
    <artifactId>json-path</artifactId>
</dependency>
```

At least that worked for me.
