### ISSUE TITLE
Unable to stream mkv files

### ISSUE THREAD

**Issue by Pipodi** [paulcwarren/spring-content#72]
I'm unable to run my Spring application if I add this dipendency:

`<dependency>
            <groupId>com.github.paulcwarren</groupId>
            <artifactId>spring-content-rest</artifactId>
            <version>0.0.9</version>
        </dependency>`

I get this error:

`2019-06-21 09:22:56.491 ERROR 3924 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'storeRestController' defined in URL [jar:file:/home/pipodi/.m2/repository/com/github/paulcwarren/spring-content-rest/0.0.9/spring-content-rest-0.0.9.jar!/internal/org/springframework/content/rest/controllers/StoreRestController.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.content.rest.config.RestConfiguration': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.content.rest.config.RestConfiguration$$EnhancerBySpringCGLIB$$88938967]: Constructor threw exception; nested exception is java.lang.NoSuchMethodError: org.springframework.data.web.config.HateoasAwareSpringDataWebConfiguration: method <init>()V not found
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1341) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1187) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:849) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877) ~[spring-context-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) ~[spring-boot-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) ~[spring-boot-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) ~[spring-boot-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) ~[spring-boot-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at it.pipodi.naspi.NasPi.main(NasPi.java:15) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:567) ~[na:na]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) ~[spring-boot-devtools-2.1.4.RELEASE.jar:2.1.4.RELEASE]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.content.rest.config.RestConfiguration': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.content.rest.config.RestConfiguration$$EnhancerBySpringCGLIB$$88938967]: Constructor threw exception; nested exception is java.lang.NoSuchMethodError: org.springframework.data.web.config.HateoasAwareSpringDataWebConfiguration: method <init>()V not found
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1303) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1197) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:392) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1321) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1160) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1247) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1167) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	... 24 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.content.rest.config.RestConfiguration$$EnhancerBySpringCGLIB$$88938967]: Constructor threw exception; nested exception is java.lang.NoSuchMethodError: org.springframework.data.web.config.HateoasAwareSpringDataWebConfiguration: method <init>()V not found
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:184) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1295) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	... 45 common frames omitted
Caused by: java.lang.NoSuchMethodError: org.springframework.data.web.config.HateoasAwareSpringDataWebConfiguration: method <init>()V not found
	at org.springframework.content.rest.config.RestConfiguration.<init>(RestConfiguration.java:16) ~[spring-content-rest-0.0.9.jar:na]
	at org.springframework.content.rest.config.RestConfiguration$$EnhancerBySpringCGLIB$$88938967.<init>(<generated>) ~[spring-content-rest-0.0.9.jar:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[na:na]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:172) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	... 47 common frames omitted`

If I remove this dipendency, the application boots. I want to implement a REST streaming endpoint.

**Comment by paulcwarren** [comment]
Hi @Pipodi ,

Looks like a dependency mismatch somewhere along the line.

What version of Spring Boot?  Spring Data?  Spring Web MVC are you using?  

Also, is there a reason why u are using Spring Content 0.0.9?  That is a pretty old version of Spring Content that was built against Spring Boot 1.x dependencies.   Spring Content 0.9.0 (as of now) is built against Spring Boot 2.1.x dependencies.  The soon to be released 1.0.0.M1 (and therefore 1.0.0.M1-SNAPSHOT only available currently) is built against Spring Boot 2.2 dependencies.

**Comment by paulcwarren** [comment]
Ping

Did that help at all @Pipodi.  Or are you still stuck with this?

**Comment by Pipodi** [comment]
Hi, @paulcwarren ,

I'm currently busy at work, I couldn't read your post untill now.

That's my fault, I wrote that wrong on my POM. With the correct version (0.9.0), it now boots, but I can't make the video streamable.

My situation is:

/home/pipodi/Movies -> is my spring.content.fs.filesystem-root value
/home/pipodi/Movies/test.mp4 -> is the file I want to stream

I've added this interface to my "main" class:

`@StoreRestResource(path = "streamtest")
	public interface VideoStore extends Store<String> {
	}`

So, I suppose my video will be reachable from:
localhost:8080/streamtest/test.mp4

but I get a 404.

**Comment by Pipodi** [comment]
Also, I just saw on logs this warning:

`Locations list is empty. No resources will be served unless a custom ResourceResolver is configured as an alternative to PathResourceResolver.`

**Comment by Pipodi** [comment]
Ok, now it works. It was a permission problem. But I have a question. MP4 files are streamed without any problem on Chrome, but when I try to stream a .mkv file, Chrome starts to download the file. It has to be with something on the request/response handled by Chrome, because I'm able to stream the mkv file from VLC.

**Comment by paulcwarren** [comment]
OK.  We should investigate that then.  Do you have a sample app that you can share?  If not I can create one and see if I can reproduce the problem.

**Comment by paulcwarren** [comment]
Re the warning.  We already have that as an [open issue](https://github.com/paulcwarren/spring-content/issues/58).   Will fix that in the next release.

**Comment by Pipodi** [comment]
@paulcwarren I've just uploaded an example here: https://github.com/Pipodi/demo-springcontent

You can find the same video under the /video/ folder, in the mp4 and mkv format.

**Comment by paulcwarren** [comment]
Thanks.  I will take a look at this and see if I can repo and then root cause the issue

**Comment by paulcwarren** [comment]
I was able to repro this to some extent @Pipodi but in general, this seemed to work for me.

So with this html:
```
<video width="320" height="240" controls>
    <source src="/stream/Kevon-Carter.mkv">
</video>
```
playback was ok.   As was this:
```
<video width="320" height="240" controls>
    <source src="/stream/Kevon-Carter.mkv" type="video/webm">
</video>
```
And this:
```
<video width="320" height="240" controls>
    <source src="/stream/Kevon-Carter.mkv" type="video/mp4">
</video>
```

But with this html:
```
<video width="320" height="240" controls>
    <source src="/stream/Kevon-Carter.mkv" type="video/mkv">
    Your browser does not support the video tag.
</video>
```
playback was not possible.  Also not possible with this html:
```
<video width="320" height="240" controls>
    <source src="/stream/Kevon-Carter.mkv" type="video/x-matroska">
</video>
``` 

Looking into this a little bit it seems like Chrome [offers support for matroska](https://www.chromium.org/audio-video) through the [webm container format](https://stackoverflow.com/questions/16940520/how-to-play-mkv-files-using-html5-video-tag).  My guess is if you explicitly tell it to use `video/webm` or if you omit the `type` altogether and the extension is `.mkv` it will use the `webm` container and it plays.  Not sure why it worked when I specified `video/mp4`.  Maybe because the video you supplied is actually mp4/aac (according to VLC anyways). 

If you were using the same html with any of the type specifications and it still didnt work for you then maybe [your chrome needs updating](https://caniuse.com/#feat=webm)?  Doubtful though as you'd have to be running a super old chrome for it not to work I think.  

I'll stop there and let you respond so we can get on the same page as to the client side of things.  I'll PR my HTML back to you so you can run the same client code that I did.

**Comment by paulcwarren** [comment]
Updated title to more accurately reflect the issue under investigation.

**Comment by paulcwarren** [comment]
Closing due to inactivity. Please feel free to re-open if you still have an issue.
